### ISSUE TITLE
What values to use for FieldName, FieldHandle, and FieldID?

### ISSUE THREAD

**Issue by KatieMFritz** [born05/craft-assetusage#13]
Hello! This plugin is awesome - my client has a lot of assets but isn't using many, so this helps her keep track. 🎉 😎 

She'd like to be able to sort by how often assets are used. I'm using module code suggested by Brandon in [this issue](https://github.com/craftcms/cms/issues/2818#issuecomment-447983635), and it's working for normal fields, but I'm not sure what values to use for the `assetusage` field created by this plugin.

What would you recommend for `<FieldName>`, `<FieldHandle>`, and `<FieldID>` in the following code?

```php
       $event->sortOptions[] = [
            'label' => '<FieldName>',
            'orderBy' => 'field_<FieldHandle>',
            'attribute' => 'field:<FieldID>'
        ];
```

**Comment by roelvanhintum** [comment]
Hi @KatieMFritz, i'm sorry but i cannot sort on the usage table because the data is processed on viewing. #5 discusses this. Craft only allows sorting on fields stored in the database (as far as i know).

Also note that unused means not coupled. I still have an issues with images in redactor (RichText) and some plugin fields.

**Comment by KatieMFritz** [comment]
Oh, okay. That makes sense. Thanks for the prompt reply!
