### ISSUE TITLE
Doesn't recognise assets linked to from Redactor

### ISSUE THREAD

**Issue by darylknight** [born05/craft-assetusage#2]
This isn't picking up on files that are used in rich text fields - will that ever happen? I've got a Redactor 2 field here which links to multiple PDFs and they're all reported as Unused.

Thanks!

**Comment by roelvanhintum** [comment]
I don't know right now how to pick those up, but i will look into it. It should count as usage. Usually i prevent asset usage in rich text fields to be able to force transforms on images etc.

**Comment by darylknight** [comment]
I totally agree with you - and I'm in the middle of converting a site from using rich text editors that allow images to a content matrix where they have to add image blocks - but there's a lot left over in the interim - it also wouldn't solve the issue of linked files rather than images :)

**Comment by roelvanhintum** [comment]
It seems that Craft has no support for relations in RichText fields. To build this, it would involve a lot of time i unfortunately don't have. I am also afraid it would cause a huge performance hit because every richtext field for every entry, category, tag, global and matrix has to be searched per asset.

It would be best if this would be correctly implemented into the Craft core's `relatedTo` functionality where it belongs.

**Comment by darylknight** [comment]
No worries - I get that. Hopefully I'll get a chance to go through the current site and change all those rich text images to asset fields. Thanks for the great work Roel!
