### ISSUE TITLE
Feature request - show where asset is being used.

### ISSUE THREAD

**Issue by anchovy** [born05/craft-assetusage#26]
Hi 

Great plugin - thanks.

Be great if this could show a tooltip with the entry/element (i.e. commerce product) that's using the asset; any chance of this happening?

Regards
Ben

**Comment by roelvanhintum** [comment]
@anchovy thanks! This is somewhat related to showing correct usage numbers. We're still working on this. Hopefully we can find a solution and include this at the same time.

**Comment by anchovy** [comment]
@roelvanhintum / Great; thanks for the reply. If I can help let me know!

**Comment by RyanRoberts** [comment]
This would be very handy! :)

**Comment by dr-codswallop** [comment]
Another vote for the possibility of seeing WHERE an asset is being used 🙏

**Comment by RitterKnightCreative** [comment]
Along these same lines, it would be useful to show that information on the sidebar area when you visit the asset in question. Right now the only way to see the used information is to put the assets browser in table/list view.  This might also help with performance since you're only querying one asset relation instead of many.

**Comment by codename-niels** [comment]
This feature is added in [3.2.0](https://github.com/born05/craft-assetusage/releases/tag/3.2.0)
Please let us know! (Or create a PR)
